baseurl: "/Beacon"
repository: dotStart/Beacon

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Social Links
social:
  discord: 'https://discord.gg/VTvSvN4ZQJ'
  github: 'https://github.com/dotStart/Beacon'
  twitter: 'https://twitter.com/dot_start'
